spring:
  application:
    name: ToyBackend
  profiles:
    active: develop
server:
  port: 8082
  tomcat:
    accesslog:
      enabled: true
file:
  uploadDir: uploads
springdoc:
  swagger-ui:
    path: /swagger-doc