# conexão com banco de dados do container local
# preparação para um ambiente em uma máquina em nuvem
spring:
  datasource:
    url: jdbc:postgresql://postgres:5433/toysdb
    username: root
    password: docker
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger-doc